Create Database Brazilian_E_Commerce;
Rename table olist_customers_dataset to customers_data;
Rename table olist_order_items_dataset to order_items;
Rename table olist_order_payments_dataset to Payment_data;
Rename table olist_orders_dataset to orders;
Rename table olist_products_dataset to products;
Rename table olist_sellers_dataset to Sellers;


-- Q1. How many total orders are present in the dataset?

select
count(distinct (order_id))
from orders;

-- Q2. What is the total revenue generated across all orders?

select
sum(payment_value)
from Payment_data;

-- Q3. How many unique customers are there?

select
count(distinct customer_unique_id)
from customers_data;

-- Q4. Which payment type is used the most?

select
payment_type,
count(payment_type) as Payment_type_count
from Payment_data
group by payment_type
order by Payment_type_count Desc
limit 1;


-- Q5. What is the total number of sellers in the dataset?

select
count(distinct (seller_id))
from Sellers;

-- Q6. What is the monthly trend of total orders?

select
monthname(order_purchase_timestamp) as order_month,
Year (order_purchase_timestamp) as order_year,
count(order_id)
from orders
group by order_month, order_year;


-- Q7. Which are the top 10 cities with the highest number of customers?

select
count(DISTINCT customer_unique_id) as total_customers,
customer_city
from customers_data
group by customer_city
order by total_customers desc
limit 10;


-- Q8. What is the average order value (AOV)?

SELECT 
ROUND(SUM(payment_value) / COUNT(DISTINCT order_id), 2) AS avg_order_value
FROM payment_data;

-- Q9. Which product categories have the highest number of sales?

select
product_category_name,
count(order_item_id) as total_sale
from products p
JOIN order_items oi
ON p.product_id = oi.product_id
group by product_category_name
order by total_sale desc;

-- Q10. What is the total revenue generated by each state?

select
customer_state,
sum(payment_value) as total_revenue
from orders o
JOIN payment_data pd
ON pd.order_id = o.order_id
JOIN customers_data cd
on cd.customer_id = o.customer_id
group by customer_state;

-- Q11. What is the average number of installments used in payments?

select
avg(payment_installments),
payment_type
from payment_data
group by payment_type;

-- Q12. Which sellers have fulfilled the highest number of orders?

select
seller_id,
count(order_item_id) as total_order
from order_items oi
group by seller_id
order by total_order desc
Limit 1;

-- Q13. Who are the top 10 customers based on total spending?

Select
customer_unique_id,
sum(payment_value),
RANK() over(order by sum(payment_value) desc)
from customers_data cd
JOIN orders o
ON o.customer_id = cd.customer_id
JOIN Payment_data pd
ON o.order_id = pd.order_id
group by customer_unique_id
order by sum(payment_value) desc
limit 10;


-- Q14. Which sellers generate the highest revenue?

select
s.seller_id,
sum(payment_value),
RANK() over(order by sum(payment_value) desc)
from sellers s
Join order_items oi
ON s.seller_id = oi.seller_id
Join Payment_data pd
ON pd.order_id = oi.order_id
group by s.seller_id
order by sum(payment_value) desc;

-- Q15. What percentage of orders are delivered after the estimated delivery date?

SELECT
COUNT(CASE WHEN order_delivered_customer_date > order_estimated_delivery_date THEN 1 END) AS delayed_orders,
count(order_id) as total_orders,
COUNT(CASE WHEN order_delivered_customer_date > order_estimated_delivery_date THEN 1 END) *100 /count(order_id) as total_orders
from orders;
 
-- Q16. Which product categories have the highest average price?

select
product_category_name,
avg(price),
Rank() over(order by avg(price) desc)
from products p
Join order_items oi
ON p.product_id = oi.product_id
group by product_category_name
order by avg(price) desc;
